[
  {
    officelocation: "Hyderabad",
    employeename: "Achyuta Samanta",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Chennai",
    employeename: "Ajay Piramal",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Bangalore",
    employeename: "Anand Mahindra",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Kochi",
    employeename: "Anil Agarwal",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Ahmedabad",
    employeename: "Anil Ambani",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Mumbai",
    employeename: "Ardeshir Godrej",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Kolkata",
    employeename: "Aroon Purie",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Chandigarh",
    employeename: "Azim Premji",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Haryana",
    employeename: "Baba Kalyani",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Pune",
    employeename: "C. J. George",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Hyderabad",
    employeename: "Binny Bansal",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Chennai",
    employeename: "Bhavish Aggarwal",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Bangalore",
    employeename: "Bhavin Turakhia",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Kochi",
    employeename: "Balkrishna",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Ahmedabad",
    employeename: "Faisal Farooqui",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Mumbai",
    employeename: "Ekta Kapoor",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Kolkata",
    employeename: "Dilip Shanghvi",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Chandigarh",
    employeename: "Deep Kalra",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Haryana",
    employeename: "Cyrus S. Poonawalla",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Pune",
    employeename: "Chenraj Roychand",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Hyderabad",
    employeename: "C. J. George",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Chennai",
    employeename: "Binny Bansal",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Bangalore",
    employeename: "Bhavish Aggarwal",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Kochi",
    employeename: "Bhavin Turakhia",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Ahmedabad",
    employeename: "Gautam Adani",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Mumbai",
    employeename: "G. R. Gopinath",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Kolkata",
    employeename: "Falguni Nayar",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Chandigarh",
    employeename: "Gunupati Venkata Krishna Reddy",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Haryana",
    employeename: "Grandhi Mallikarjuna Rao",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Pune",
    employeename: "Gautam Thapar",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Hyderabad",
    employeename: "Jamnalal Bajaj",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Chennai",
    employeename: "Jagdish Chandra Mahindra",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Bangalore",
    employeename: "Harsh Mariwala",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Kochi",
    employeename: "Kalanithi Maran",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Ahmedabad",
    employeename: "K. M. Vasudevan Pillai",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Mumbai",
    employeename: "Rahul Bajaj",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Kolkata",
    employeename: "Kavin Bharti Mittal",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Chandigarh",
    employeename: "Karsanbhai Patel",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Haryana",
    employeename: "Kallam Anji Reddy",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Pune",
    employeename: "Kochouseph Chittilappilly",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Hyderabad",
    employeename: "Kishore Biyani",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Chennai",
    employeename: "Kiran Mazumdar-Shaw",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Bangalore",
    employeename: "Lakshmi Mittal",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Kochi",
    employeename: "Kunwer Sachdev",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Ahmedabad",
    employeename: "Kumar Mangalam Birla",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Mumbai",
    employeename: "M. M. Murugappan",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Kolkata",
    employeename: "M.A. Yusuff Ali",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Chandigarh",
    employeename: "Laxmanrao Kirloskar",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Haryana",
    employeename: "Moothedath Panjan Ramachandra",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Pune",
    employeename: "Mangal Lodha",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Hyderabad",
    employeename: "Mallika Srinivasan",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Chennai",
    employeename: "N. S. Raghavan",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Bangalore",
    employeename: "N. R. Narayana Murthy",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Kochi",
    employeename: "Mukesh Ambani",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Ahmedabad",
    employeename: "Naveen Jain",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Mumbai",
    employeename: "Keshav Bansal",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Kolkata",
    employeename: "Narendra Bansal",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Chandigarh",
    employeename: "Prannoy Roy",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Haryana",
    employeename: "Pradeep Kar",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Pune",
    employeename: "Nikhil Kamath",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Hyderabad",
    employeename: "Radhakishan Damani",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Chennai",
    employeename: "R. P. Goenka",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Bangalore",
    employeename: "Prathap C. Reddy",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Kochi",
    employeename: "Ratan Tata",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Ahmedabad",
    employeename: "Ramoji Rao",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Mumbai",
    employeename: "Radhika Aggarwal",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Kolkata",
    employeename: "Kunal Bahl",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Chandigarh",
    employeename: "Rohit Bansal",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Haryana",
    employeename: "Ritesh Agarwal",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Pune",
    employeename: "Ravi Ruia",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Hyderabad",
    employeename: "Shashi",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Chennai",
    employeename: "Samprada Singh",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Bangalore",
    employeename: "Sridhar Vembu",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Kochi",
    employeename: "Srichand Hinduja",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Ahmedabad",
    employeename: "Shiv Nadar",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Mumbai",
    employeename: "Sunil Mittal",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Kolkata",
    employeename: "Sunil John",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Chandigarh",
    employeename: "Subrata Roy",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Haryana",
    employeename: "V. G. Siddhartha",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Pune",
    employeename: "Uday Kotak",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Hyderabad",
    employeename: "Trishneet Arora",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Chennai",
    employeename: "Verghese Kurien",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Bangalore",
    employeename: "Venugopal Dhoot",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Kochi",
    employeename: "Venu Srinivasan",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Ahmedabad",
    employeename: "Vishal Gondal",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Mumbai",
    employeename: "Vijay Shekhar Sharma",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Kolkata",
    employeename: "Vijay Mallya",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Chandigarh",
    employeename: "Piper Marin",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Haryana",
    employeename: "Henrik Lawson",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Pune",
    employeename: "Felicity Perez",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Hyderabad",
    employeename: "Tomas Hopkins",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Chennai",
    employeename: "Christina Clayton",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Bangalore",
    employeename: "Calum Davidson",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Kochi",
    employeename: "Kiana Molina",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Ahmedabad",
    employeename: "Zev Estes",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Mumbai",
    employeename: "Paislee Fields",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Kolkata",
    employeename: "Jakobe Barry",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Chandigarh",
    employeename: "Monica Lawson",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Haryana",
    employeename: "Phoenix Chan",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Pune",
    employeename: "Carly Huerta",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Hyderabad",
    employeename: "Finn Tucker",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Chennai",
    employeename: "Kaylie Gaines",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Bangalore",
    employeename: "Zayne Robles",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Kochi",
    employeename: "Paisleigh Spears",
    workingfromname: "home",
    projectname: "Amazon",
  },
  {
    officelocation: "Ahmedabad",
    employeename: "Grey Le",
    workingfromname: "home",
    projectname: "Netflix",
  },
  {
    officelocation: "Mumbai",
    employeename: "Lola Washington",
    workingfromname: "office",
    projectname: "Meta",
  },
  {
    officelocation: "Kolkata",
    employeename: "Nicholas Weiss",
    workingfromname: "office",
    projectname: "Amazon",
  },
  {
    officelocation: "Chandigarh",
    employeename: "Mae Summers",
    workingfromname: "office",
    projectname: "Netflix",
  },
  {
    officelocation: "Haryana",
    employeename: "Roman Pruitt",
    workingfromname: "home",
    projectname: "Meta",
  },
  {
    officelocation: "Pune",
    employeename: "Aliyah Gilbert",
    workingfromname: "home",
    projectname: "Amazon",
  },
];